### ISSUE TITLE
url issue after craft 5 upgrade

### ISSUE THREAD

**Issue by samuelbirch** [spacecatninja/craft-imager-x-aws-serverless-transformer#11]
After upgrading to craft5, we are now getting a 
`code: "NoSuchKey"`
on transformed images with the message:
`"The image images/xxxxxxx.png does not exist or the request may not be base64 encoded properly."`

**Comment by samuelbirch** [comment]
found the issue...

a double `//` is causing it. 

i'll submit a PR

**Comment by samuelbirch** [comment]
https://github.com/spacecatninja/craft-imager-x-aws-serverless-transformer/pull/12

**Comment by aelvan** [comment]
Thank you, this has been merged into 3.0.2.
