### ISSUE TITLE
 Transforming external images

### ISSUE THREAD

**Issue by umkasanki** [spacecatninja/craft-imager-x-aws-serverless-transformer#2]
Hello

Got an error when trying to change an image from a link.
Sample code. (Work as expected with `'transformer' => 'craft',`, error with `'transformer' => 'awsserverless',`)
```
{% for image in craft.assets.id(28446).all() %}
    <h1>Imager from asset</h1>
    {% set transform = craft.imagerx.transformImage(image, {
        height: 600,
        width: 600
    }) %}
    <img src="{{ transform.url }}" width="200">
    <p>URL is: {{ transform.url }}</p>

    <h1>Imager from image</h1>
    {% set transform = craft.imagerx.transformImage(image.url, {
        height: 600,
        width: 600
    }) %}
    <img src="{{ transform.url }}" width="200">
    <p>URL is: {{ transform.url }}</p>
{% endfor %}
```

Error
![transformer-awsserverless](https://user-images.githubusercontent.com/496132/188921620-559ebd1a-90b9-44ef-a1a8-6c5913f50ef5.png)

Craft CMS 3.7.47.1
Amazon S3 v1.3.0
Imager X v3.6.1
Imager X AWS Serverless Transformer v1.0.0

Thanks

**Comment by aelvan** [comment]
Hi, 

Yes, that's a limitation with this transformer, it can only transform assets that resides on the S3 bucket that the handler is set up to process. I've noted this in the cave-ats section.

> Only assets that are stored in AWS buckets are possible to transform.

**Comment by umkasanki** [comment]
Got it.
Thanks
