### ISSUE TITLE
Account for all-caps in file extension

### ISSUE THREAD

**Issue by chadwells** [spacecatninja/craft-imager-x-aws-serverless-transformer#9]
The AWS Serverless Image Handler does not like it when it tries to transform an image that has a filename that is ALL-CAPS such as `image.JPG`, and will give an error. 

This can be fixed by changing this:
https://github.com/spacecatninja/craft-imager-x-aws-serverless-transformer/blob/697a58756655d748f3b14e4c414fe2f2483c7277/src/transformers/AwsServerless.php#L35-L37

To this:
```php
    public static array $formatTranslate = [
        'jpg' => 'jpeg',
        'JPG' => 'jpeg',
        'JPEG' => 'jpeg',
        'PNG' => 'png'
    ];
```

We use plugin v2.1.0 on Craft 4

**Comment by daniellelecomte** [comment]
Could also use this fix @aelvan!

**Comment by alexmglover** [comment]
Also need this, thanks in advance!

**Comment by aelvan** [comment]
It's been merged into both the Craft 4 and 5 versions. Thanks for contributing, @chadwells.

**Comment by chadwells** [comment]
Thanks @aelvan!
